# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 4
palette:
  white: "#FFFFFF"
  tan: "#CC3802"
  teal: "#047E84"
  plum: "#9A348E"
  blush: "#DA627D"
  salmon: "#FCA17D"
  sky: "#86BBD8"
  teal_blue: "#33658A"
  orange: "#ffa500"
blocks:
  - type: "prompt"
    alignment: "left"
    segments:
      - type: "status"
        background: "p:teal_blue"
        "background_templates":
          - "{{ if gt .Code 0 }}#ff6347{{ end }}"
        foreground: "p:white"
        options:
          always_enabled: true
        leading_diamond: "\ue0b6"
        style: "diamond"
        template: " {{ if gt .Code 0 }}\uf00d {{ reason .Code }}{{ else }}\uf00c{{ end }} "
      - type: "path"
        background: "p:sky"
        foreground: "p:white"
        powerline_symbol: "\ue0b0"
        options:
          style: "full"
        style: "powerline"
        template: " {{ .Path }} "
      - type: "git"
        background: "p:orange"
        foreground: "p:white"
        powerline_symbol: "\ue0b0"
        options:
          fetch_upstream_icon: true
        style: "powerline"
        template: " {{ .UpstreamIcon }} {{ .HEAD }} {{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
