# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 4
palette:
  white: "#FFFFFF"
  tan: "#CC3802"
  teal: "#047E84"
  plum: "#9A348E"
  blush: "#DA627D"
  salmon: "#FCA17D"
  sky: "#86BBD8"
  teal_blue: "#33658A"
blocks:
  - type: "rprompt"
    alignment: "left"
    segments:
      - type: "text"
        style: "diamond"
        leading_diamond: "\ue0b6"
        foreground: "p:white"
        background: "p:tan"
        template: "{{ if .Env.PNPPSHOST }} \uf8c5 {{ .Env.PNPPSHOST }} {{ end }}"
      - type: "text"
        style: "powerline"
        foreground: "p:white"
        background: "p:teal"
        powerline_symbol: "\ue0b0"
        template: "{{ if .Env.PNPPSSITE }} \uf2dd {{ .Env.PNPPSSITE }}{{ end }}"
      - type: "text"
        style: "diamond"
        trailing_diamond: "\ue0b4"
        foreground: "p:white"
        background: "p:teal"
        template: "{{ if .Env.PNPPSSITE }}\u00A0{{ end }}"
  - type: "prompt"
    alignment: "left"
    segments:
      - type: "session"
        background: "p:teal_blue"
        foreground: "p:white"
        leading_diamond: "\ue0b6"
        style: "diamond"
        template: "{{ .UserName }} "
      - type: "path"
        background: "p:sky"
        foreground: "p:white"
        powerline_symbol: "\ue0b0"
        options:
          style: "folder"
        style: "powerline"
        template: " {{ .Path }} "
      - type: "git"
        background: "p:salmon"
        foreground: "p:white"
        powerline_symbol: "\ue0b0"
        options:
          branch_icon: ""
          fetch_status: true
          fetch_upstream_icon: true
        style: "powerline"
        template: " {{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
